import Head from "next/head";
import { Inter } from "@next/font/google";
import { Icon } from "@/components/Icon";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Icons</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Icon name="file-download" />
			<Icon name="file-upload" />
			<Icon name="add" />
			<Icon name="chevron-left" />
			<Icon name="arrow-forward" />
			<Icon name="chevron-right" />
		</>
	);
}
